---
galaxy_info:
  author: Rin Team
  description: Setup homelab server with Nginx and SSL
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  
  galaxy_tags:
    - homelab
    - nginx
    - ssl
    - webserver

dependencies:
  - role: common
