---
galaxy_info:
  author: Rin Team
  description: Deploy Rin to Cloudflare Workers
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  
  galaxy_tags:
    - cloudflare
    - workers
    - deployment

dependencies: []
